name: Unzip and Commit

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Unzip the file
        run: |
          ZIP="download (1).zip"
          if [ -f "$ZIP" ]; then
            mkdir -p extracted
            unzip -o "$ZIP" -d extracted
          else
            echo "$ZIP not found"; exit 1
          fi

      - name: Move extracted files to repo root
        run: |
          shopt -s dotglob
          cp -a extracted/. .
          rm -rf extracted

      - name: Remove the zip file
        run: rm -f "download (1).zip"

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Extracted download (1).zip via workflow"
            git push
          fi